name: Publish javadoc to GitHub pages

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build javadoc
        run: ./gradlew dokkaHtmlMultiModule
      - name: Publish to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/dokka
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}